// <auto-generated />
namespace AppWebHojaCosto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigracionHojaCostoV17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracionHojaCostoV17));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061508215_MigracionHojaCostoV17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
