// <auto-generated />
namespace AppWebHojaCosto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambio_parametro_int_precosteo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambio_parametro_int_precosteo));
        
        string IMigrationMetadata.Id
        {
            get { return "202003060343530_cambio_parametro_int_precosteo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
