// <auto-generated />
namespace AppWebHojaCosto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambio_campo_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambio_campo_int));
        
        string IMigrationMetadata.Id
        {
            get { return "202002241932246_cambio_campo_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
