//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.Parametros {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.Parametros.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén línea.
        /// </summary>
        public static string tet_gastos_finan_almacen {
            get {
                return ResourceManager.GetString("tet_gastos_finan_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén línea.
        /// </summary>
        public static string tet_gastos_gen_almacen {
            get {
                return ResourceManager.GetString("tet_gastos_gen_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén línea.
        /// </summary>
        public static string tet_gastos_vnts_almacen {
            get {
                return ResourceManager.GetString("tet_gastos_vnts_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrativos.
        /// </summary>
        public static string text_administrativos {
            get {
                return ResourceManager.GetString("text_administrativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colección.
        /// </summary>
        public static string text_coleccion {
            get {
                return ResourceManager.GetString("text_coleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter price.
        /// </summary>
        public static string text_enter_price {
            get {
                return ResourceManager.GetString("text_enter_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string text_factor {
            get {
                return ResourceManager.GetString("text_factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor rentabilidad mínimo.
        /// </summary>
        public static string text_factor_max {
            get {
                return ResourceManager.GetString("text_factor_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor rentabilidad máximo.
        /// </summary>
        public static string text_factor_min {
            get {
                return ResourceManager.GetString("text_factor_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financiero.
        /// </summary>
        public static string text_financieros {
            get {
                return ResourceManager.GetString("text_financieros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Insumos.
        /// </summary>
        public static string text_gasto_insumo {
            get {
                return ResourceManager.GetString("text_gasto_insumo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Telas.
        /// </summary>
        public static string text_gasto_tela {
            get {
                return ResourceManager.GetString("text_gasto_tela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén línea.
        /// </summary>
        public static string text_gastos_almacen {
            get {
                return ResourceManager.GetString("text_gastos_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor USD.
        /// </summary>
        public static string text_gastos_finan_usd {
            get {
                return ResourceManager.GetString("text_gastos_finan_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor USD.
        /// </summary>
        public static string text_gastos_gen_usd {
            get {
                return ResourceManager.GetString("text_gastos_gen_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor USD.
        /// </summary>
        public static string text_gastos_usd {
            get {
                return ResourceManager.GetString("text_gastos_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mayor USD.
        /// </summary>
        public static string text_gastos_vnts_usd {
            get {
                return ResourceManager.GetString("text_gastos_vnts_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IVA.
        /// </summary>
        public static string text_iva {
            get {
                return ResourceManager.GetString("text_iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string text_linea {
            get {
                return ResourceManager.GetString("text_linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string text_marca {
            get {
                return ResourceManager.GetString("text_marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen máximo %.
        /// </summary>
        public static string text_margen_max_util {
            get {
                return ResourceManager.GetString("text_margen_max_util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen mínimo %.
        /// </summary>
        public static string text_margen_min_util {
            get {
                return ResourceManager.GetString("text_margen_min_util", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adicional por mayor USD %.
        /// </summary>
        public static string text_margen_usd {
            get {
                return ResourceManager.GetString("text_margen_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium price.
        /// </summary>
        public static string text_medium_price {
            get {
                return ResourceManager.GetString("text_medium_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadeo.
        /// </summary>
        public static string text_mercadeo {
            get {
                return ResourceManager.GetString("text_mercadeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacén línea %.
        /// </summary>
        public static string text_participacion_almacen {
            get {
                return ResourceManager.GetString("text_participacion_almacen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor cociente 2.
        /// </summary>
        public static string text_PpCocienteDivisor2F {
            get {
                return ResourceManager.GetString("text_PpCocienteDivisor2F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor cociente 1.
        /// </summary>
        public static string text_PpCocienteDivisorF {
            get {
                return ResourceManager.GetString("text_PpCocienteDivisorF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrativos.
        /// </summary>
        public static string text_PpParticipacionAdminF {
            get {
                return ResourceManager.GetString("text_PpParticipacionAdminF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financieros.
        /// </summary>
        public static string text_PpParticipacionFinanF {
            get {
                return ResourceManager.GetString("text_PpParticipacionFinanF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadeo.
        /// </summary>
        public static string text_PpParticipacionMercadeoF {
            get {
                return ResourceManager.GetString("text_PpParticipacionMercadeoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor máximo precios.
        /// </summary>
        public static string text_PpPrecioMaximoF {
            get {
                return ResourceManager.GetString("text_PpPrecioMaximoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor mínimo precios.
        /// </summary>
        public static string text_PpPrecioMinimoF {
            get {
                return ResourceManager.GetString("text_PpPrecioMinimoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor residuo.
        /// </summary>
        public static string text_PpResiduoDivisorF {
            get {
                return ResourceManager.GetString("text_PpResiduoDivisorF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Terminación precios.
        /// </summary>
        public static string text_PpTerminoPrecioF {
            get {
                return ResourceManager.GetString("text_PpTerminoPrecioF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tope indicador decimales.
        /// </summary>
        public static string text_PpTopePrecioMilesF {
            get {
                return ResourceManager.GetString("text_PpTopePrecioMilesF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premium price.
        /// </summary>
        public static string text_premium_price {
            get {
                return ResourceManager.GetString("text_premium_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubLinea.
        /// </summary>
        public static string text_sub_linea {
            get {
                return ResourceManager.GetString("text_sub_linea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa cambio colección.
        /// </summary>
        public static string text_tasa_coleccion {
            get {
                return ResourceManager.GetString("text_tasa_coleccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa cambio especial.
        /// </summary>
        public static string text_tasa_especial {
            get {
                return ResourceManager.GetString("text_tasa_especial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa cambio EUR/USD.
        /// </summary>
        public static string text_tasa_eur {
            get {
                return ResourceManager.GetString("text_tasa_eur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Admin y financieros.
        /// </summary>
        public static string text_tope_admin {
            get {
                return ResourceManager.GetString("text_tope_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadeo.
        /// </summary>
        public static string text_tope_mercadeo {
            get {
                return ResourceManager.GetString("text_tope_mercadeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas x canal línea.
        /// </summary>
        public static string text_tope_vnts {
            get {
                return ResourceManager.GetString("text_tope_vnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRM.
        /// </summary>
        public static string text_trm {
            get {
                return ResourceManager.GetString("text_trm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen de utilidad.
        /// </summary>
        public static string titulo_margen_utilidad {
            get {
                return ResourceManager.GetString("titulo_margen_utilidad", resourceCulture);
            }
        }
    }
}
