//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.HojaEstandar {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AnalisisPrecios {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalisisPrecios() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.HojaEstandar.AnalisisPrecios", typeof(AnalisisPrecios).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_ApMargenMaxBrutoEstF {
            get {
                return ResourceManager.GetString("text_ApMargenMaxBrutoEstF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_ApMargenMaxBrutoRealF {
            get {
                return ResourceManager.GetString("text_ApMargenMaxBrutoRealF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_ApMargenMaxOpeEstF {
            get {
                return ResourceManager.GetString("text_ApMargenMaxOpeEstF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_ApMargenMaxOpeRealF {
            get {
                return ResourceManager.GetString("text_ApMargenMaxOpeRealF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_ApMargenMinBrutoEstF {
            get {
                return ResourceManager.GetString("text_ApMargenMinBrutoEstF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_ApMargenMinBrutoRealF {
            get {
                return ResourceManager.GetString("text_ApMargenMinBrutoRealF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_ApMargenMinOpeEstF {
            get {
                return ResourceManager.GetString("text_ApMargenMinOpeEstF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_ApMargenMinOpeRealF {
            get {
                return ResourceManager.GetString("text_ApMargenMinOpeRealF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRECIO MAXIMO CON IVA.
        /// </summary>
        public static string text_ApPrecMaxIvaEstD {
            get {
                return ResourceManager.GetString("text_ApPrecMaxIvaEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRECIO MAXIMO CON IVA.
        /// </summary>
        public static string text_ApPrecMaxIvaRealD {
            get {
                return ResourceManager.GetString("text_ApPrecMaxIvaRealD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRECIO MINIMO CON IVA.
        /// </summary>
        public static string text_ApPrecMinIvaEstD {
            get {
                return ResourceManager.GetString("text_ApPrecMinIvaEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRECIO MINIMO CON IVA.
        /// </summary>
        public static string text_ApPrecMinIvaRealD {
            get {
                return ResourceManager.GetString("text_ApPrecMinIvaRealD", resourceCulture);
            }
        }
    }
}
