//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.HojaEstandar {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.HojaEstandar.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colección.
        /// </summary>
        public static string text_HcColeccionS {
            get {
                return ResourceManager.GetString("text_HcColeccionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseñador.
        /// </summary>
        public static string text_HcDisenadorS {
            get {
                return ResourceManager.GetString("text_HcDisenadorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Price.
        /// </summary>
        public static string text_HcEnterPriceD {
            get {
                return ResourceManager.GetString("text_HcEnterPriceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado Aprobación.
        /// </summary>
        public static string text_HcEstadoAproS {
            get {
                return ResourceManager.GetString("text_HcEstadoAproS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string text_HcEstadoS {
            get {
                return ResourceManager.GetString("text_HcEstadoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string text_HcLineaS {
            get {
                return ResourceManager.GetString("text_HcLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string text_HcMarcaS {
            get {
                return ResourceManager.GetString("text_HcMarcaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Price.
        /// </summary>
        public static string text_HcMediumPriceD {
            get {
                return ResourceManager.GetString("text_HcMediumPriceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patronista.
        /// </summary>
        public static string text_HcPatronistaS {
            get {
                return ResourceManager.GetString("text_HcPatronistaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premium Price.
        /// </summary>
        public static string text_HcPremiumPriceD {
            get {
                return ResourceManager.GetString("text_HcPremiumPriceD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string text_HcReferenciaS {
            get {
                return ResourceManager.GetString("text_HcReferenciaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubLinea.
        /// </summary>
        public static string text_HcSubLineaS {
            get {
                return ResourceManager.GetString("text_HcSubLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total CIF y MOD.
        /// </summary>
        public static string text_HcTotalCIFMODM {
            get {
                return ResourceManager.GetString("text_HcTotalCIFMODM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Telas.
        /// </summary>
        public static string text_HcTotalConTelasM {
            get {
                return ResourceManager.GetString("text_HcTotalConTelasM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Costo Producción.
        /// </summary>
        public static string text_HcTotalCosPrdM {
            get {
                return ResourceManager.GetString("text_HcTotalCosPrdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Gastos.
        /// </summary>
        public static string text_HcTotalGastosM {
            get {
                return ResourceManager.GetString("text_HcTotalGastosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Insumos.
        /// </summary>
        public static string text_HcTotalInsumoM {
            get {
                return ResourceManager.GetString("text_HcTotalInsumoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Marquillas y Empaque.
        /// </summary>
        public static string text_HcTotalMarquillaM {
            get {
                return ResourceManager.GetString("text_HcTotalMarquillaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Procesos.
        /// </summary>
        public static string text_HcTotalProcesosM {
            get {
                return ResourceManager.GetString("text_HcTotalProcesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Telas.
        /// </summary>
        public static string text_HcTotalTelasM {
            get {
                return ResourceManager.GetString("text_HcTotalTelasM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Gastos x Canal.
        /// </summary>
        public static string text_HcTotalxCanalM {
            get {
                return ResourceManager.GetString("text_HcTotalxCanalM", resourceCulture);
            }
        }
    }
}
