//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.HojaEstandar {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResumenGastos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResumenGastos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.HojaEstandar.ResumenGastos", typeof(ResumenGastos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrativos.
        /// </summary>
        public static string text_RdAdminEstD {
            get {
                return ResourceManager.GetString("text_RdAdminEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrativos.
        /// </summary>
        public static string text_RdAdminRealD {
            get {
                return ResourceManager.GetString("text_RdAdminRealD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financieros.
        /// </summary>
        public static string text_RdFinanEstD {
            get {
                return ResourceManager.GetString("text_RdFinanEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financieros.
        /// </summary>
        public static string text_RdFinanRealD {
            get {
                return ResourceManager.GetString("text_RdFinanRealD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadeo.
        /// </summary>
        public static string text_RdMercadeoEstD {
            get {
                return ResourceManager.GetString("text_RdMercadeoEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mercadeo.
        /// </summary>
        public static string text_RdMercadeoRealD {
            get {
                return ResourceManager.GetString("text_RdMercadeoRealD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas x Canal.
        /// </summary>
        public static string text_RdVentasxCanalEstD {
            get {
                return ResourceManager.GetString("text_RdVentasxCanalEstD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas x Canal.
        /// </summary>
        public static string text_RdVentasxCanalRealD {
            get {
                return ResourceManager.GetString("text_RdVentasxCanalRealD", resourceCulture);
            }
        }
    }
}
