//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.HojaCostoPNP {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.HojaCostoPNP.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adecuación Producto.
        /// </summary>
        public static string text_PnpAdecuacionPrdM {
            get {
                return ResourceManager.GetString("text_PnpAdecuacionPrdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arreglo Producto.
        /// </summary>
        public static string text_PnpArregloM {
            get {
                return ResourceManager.GetString("text_PnpArregloM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Pedida.
        /// </summary>
        public static string text_PnpCntPedN {
            get {
                return ResourceManager.GetString("text_PnpCntPedN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colección.
        /// </summary>
        public static string text_PnpColeccionS {
            get {
                return ResourceManager.GetString("text_PnpColeccionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo Compra.
        /// </summary>
        public static string text_PnpCostoCompraPesosM {
            get {
                return ResourceManager.GetString("text_PnpCostoCompraPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo Compra.
        /// </summary>
        public static string text_PnpCostoCompraUSDD {
            get {
                return ResourceManager.GetString("text_PnpCostoCompraUSDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string text_PnpDescripS {
            get {
                return ResourceManager.GetString("text_PnpDescripS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Price.
        /// </summary>
        public static string text_PnpEnterPriceM {
            get {
                return ResourceManager.GetString("text_PnpEnterPriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string text_PnpEstadoS {
            get {
                return ResourceManager.GetString("text_PnpEstadoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Administrativos Ventas Estimado.
        /// </summary>
        public static string text_PnpGastosAdmonEstimadoM {
            get {
                return ResourceManager.GetString("text_PnpGastosAdmonEstimadoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Administrativos Ventas.
        /// </summary>
        public static string text_PnpGastosAdmonM {
            get {
                return ResourceManager.GetString("text_PnpGastosAdmonM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Administrativos Ventas.
        /// </summary>
        public static string text_PnpGastosAdmonRealM {
            get {
                return ResourceManager.GetString("text_PnpGastosAdmonRealM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arancel.
        /// </summary>
        public static string text_PnpGastosArancelPesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosArancelPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Destino.
        /// </summary>
        public static string text_PnpGastosDestinoPesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosDestinoPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flete Aérero.
        /// </summary>
        public static string text_PnpGastosFleteAereoM {
            get {
                return ResourceManager.GetString("text_PnpGastosFleteAereoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flete Marítimo.
        /// </summary>
        public static string text_PnpGastosFletePesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosFletePesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gasto Origen.
        /// </summary>
        public static string text_PnpGastosOrigenPesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosOrigenPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros Gastos.
        /// </summary>
        public static string text_PnpGastosOtrosPesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosOtrosPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro Internacional.
        /// </summary>
        public static string text_PnpGastosSeguroPesosM {
            get {
                return ResourceManager.GetString("text_PnpGastosSeguroPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string text_PnpLineaS {
            get {
                return ResourceManager.GetString("text_PnpLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string text_PnpMarcaS {
            get {
                return ResourceManager.GetString("text_PnpMarcaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_PnpMargenMaxBrutoEstimadoF {
            get {
                return ResourceManager.GetString("text_PnpMargenMaxBrutoEstimadoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_PnpMargenMaxOpeEstimadoF {
            get {
                return ResourceManager.GetString("text_PnpMargenMaxOpeEstimadoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Bruto %.
        /// </summary>
        public static string text_PnpMargenMinBrutoEstimadoF {
            get {
                return ResourceManager.GetString("text_PnpMargenMinBrutoEstimadoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Margen Operacional %.
        /// </summary>
        public static string text_PnpMargenMinOpeEstimadoF {
            get {
                return ResourceManager.GetString("text_PnpMargenMinOpeEstimadoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Price.
        /// </summary>
        public static string text_PnpMediumPriceM {
            get {
                return ResourceManager.GetString("text_PnpMediumPriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a País Origen.
        /// </summary>
        public static string text_PnpPaisOrigenS {
            get {
                return ResourceManager.GetString("text_PnpPaisOrigenS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin Seguridad.
        /// </summary>
        public static string text_PnpPinSeguridadPesosM {
            get {
                return ResourceManager.GetString("text_PnpPinSeguridadPesosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Máximo IVA.
        /// </summary>
        public static string text_PnpPrecioMaxEstimadoM {
            get {
                return ResourceManager.GetString("text_PnpPrecioMaxEstimadoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Máximo IVA.
        /// </summary>
        public static string text_PnpPrecioMaxRealM {
            get {
                return ResourceManager.GetString("text_PnpPrecioMaxRealM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Mínimo IVA.
        /// </summary>
        public static string text_PnpPrecioMinEstimadoM {
            get {
                return ResourceManager.GetString("text_PnpPrecioMinEstimadoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Mínimo IVA.
        /// </summary>
        public static string text_PnpPrecioMinRealM {
            get {
                return ResourceManager.GetString("text_PnpPrecioMinRealM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premium Price.
        /// </summary>
        public static string text_PnpPremiumPriceM {
            get {
                return ResourceManager.GetString("text_PnpPremiumPriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string text_PnpProveedorS {
            get {
                return ResourceManager.GetString("text_PnpProveedorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reconstrucción Producto.
        /// </summary>
        public static string text_PnpReconstruccionM {
            get {
                return ResourceManager.GetString("text_PnpReconstruccionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string text_PnpReferenciaS {
            get {
                return ResourceManager.GetString("text_PnpReferenciaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensorización.
        /// </summary>
        public static string text_PnpSensorizacionM {
            get {
                return ResourceManager.GetString("text_PnpSensorizacionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubLinea.
        /// </summary>
        public static string text_PnpSubLineaS {
            get {
                return ResourceManager.GetString("text_PnpSubLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a T. Negocio.
        /// </summary>
        public static string text_PnpTermNegocS {
            get {
                return ResourceManager.GetString("text_PnpTermNegocS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Costo Puesto Bodega.
        /// </summary>
        public static string text_PnpTotalCostoBodegaM {
            get {
                return ResourceManager.GetString("text_PnpTotalCostoBodegaM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Costos + Gastos Estimado.
        /// </summary>
        public static string text_PnpTotalCostosGastosEstimadoM {
            get {
                return ResourceManager.GetString("text_PnpTotalCostosGastosEstimadoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Costos + Gastos.
        /// </summary>
        public static string text_PnpTotalCostosGastosM {
            get {
                return ResourceManager.GetString("text_PnpTotalCostosGastosM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Costos + Gastos.
        /// </summary>
        public static string text_PnpTotalCostosGastosRealM {
            get {
                return ResourceManager.GetString("text_PnpTotalCostosGastosRealM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRM.
        /// </summary>
        public static string text_PnpTrmM {
            get {
                return ResourceManager.GetString("text_PnpTrmM", resourceCulture);
            }
        }
    }
}
