//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.Alertas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.Alertas.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Área.
        /// </summary>
        public static string text_AlAreaS {
            get {
                return ResourceManager.GetString("text_AlAreaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio.
        /// </summary>
        public static string text_AlCambioS {
            get {
                return ResourceManager.GetString("text_AlCambioS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colección.
        /// </summary>
        public static string text_AlColeccionS {
            get {
                return ResourceManager.GetString("text_AlColeccionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string text_AlDescripcionS {
            get {
                return ResourceManager.GetString("text_AlDescripcionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string text_AlEstadoS {
            get {
                return ResourceManager.GetString("text_AlEstadoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string text_AlFechaD {
            get {
                return ResourceManager.GetString("text_AlFechaD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string text_AlLineaS {
            get {
                return ResourceManager.GetString("text_AlLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string text_AlMarcaS {
            get {
                return ResourceManager.GetString("text_AlMarcaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referencia.
        /// </summary>
        public static string text_AlReferenciaS {
            get {
                return ResourceManager.GetString("text_AlReferenciaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string text_AlUsuarioS {
            get {
                return ResourceManager.GetString("text_AlUsuarioS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Actual.
        /// </summary>
        public static string text_AlValorActualM {
            get {
                return ResourceManager.GetString("text_AlValorActualM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Anterior.
        /// </summary>
        public static string text_AlValorAnteriorMS {
            get {
                return ResourceManager.GetString("text_AlValorAnteriorMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variación.
        /// </summary>
        public static string text_AlVariacionM {
            get {
                return ResourceManager.GetString("text_AlVariacionM", resourceCulture);
            }
        }
    }
}
