//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebHojaCosto.Resources.ParametrosPnp {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppWebHojaCosto.Resources.ParametrosPnp.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adecuación del producto.
        /// </summary>
        public static string text_PnAdcPrdM {
            get {
                return ResourceManager.GetString("text_PnAdcPrdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arancel.
        /// </summary>
        public static string text_PnArancelF {
            get {
                return ResourceManager.GetString("text_PnArancelF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Arreglo del producto.
        /// </summary>
        public static string text_PnArregloPrdM {
            get {
                return ResourceManager.GetString("text_PnArregloPrdM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colección.
        /// </summary>
        public static string text_PnColeccionS {
            get {
                return ResourceManager.GetString("text_PnColeccionS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor Cociente.
        /// </summary>
        public static string text_PnDivisorCocienteF {
            get {
                return ResourceManager.GetString("text_PnDivisorCocienteF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Divisor Residuo.
        /// </summary>
        public static string text_PnDivisorResiduoF {
            get {
                return ResourceManager.GetString("text_PnDivisorResiduoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Price.
        /// </summary>
        public static string text_PnEnterpriceM {
            get {
                return ResourceManager.GetString("text_PnEnterpriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor máximo.
        /// </summary>
        public static string text_PnFactorMaxF {
            get {
                return ResourceManager.GetString("text_PnFactorMaxF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor mínimo.
        /// </summary>
        public static string text_PnFactorMinF {
            get {
                return ResourceManager.GetString("text_PnFactorMinF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor.
        /// </summary>
        public static string text_PnFactorS {
            get {
                return ResourceManager.GetString("text_PnFactorS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Destino.
        /// </summary>
        public static string text_PnGastosDestF {
            get {
                return ResourceManager.GetString("text_PnGastosDestF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Estimados %.
        /// </summary>
        public static string text_PnGastosEstimadoF {
            get {
                return ResourceManager.GetString("text_PnGastosEstimadoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gatos Flete Aéreo.
        /// </summary>
        public static string text_PnGastosFleteAereroF {
            get {
                return ResourceManager.GetString("text_PnGastosFleteAereroF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Flete Marítimo.
        /// </summary>
        public static string text_PnGastosFleteF {
            get {
                return ResourceManager.GetString("text_PnGastosFleteF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Origen.
        /// </summary>
        public static string text_PnGastosOrigenF {
            get {
                return ResourceManager.GetString("text_PnGastosOrigenF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gastos Reales.
        /// </summary>
        public static string text_PnGastosRealesM {
            get {
                return ResourceManager.GetString("text_PnGastosRealesM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iva.
        /// </summary>
        public static string text_PnIvaF {
            get {
                return ResourceManager.GetString("text_PnIvaF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Línea.
        /// </summary>
        public static string text_PnLineaS {
            get {
                return ResourceManager.GetString("text_PnLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string text_PnMarcaS {
            get {
                return ResourceManager.GetString("text_PnMarcaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium Price.
        /// </summary>
        public static string text_PnMediumPriceM {
            get {
                return ResourceManager.GetString("text_PnMediumPriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros Gastos.
        /// </summary>
        public static string text_PnOtrosGastosF {
            get {
                return ResourceManager.GetString("text_PnOtrosGastosF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pin Seguridad.
        /// </summary>
        public static string text_PnPinSeguridadF {
            get {
                return ResourceManager.GetString("text_PnPinSeguridadF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje Gastos.
        /// </summary>
        public static string text_PnPorcGastosF {
            get {
                return ResourceManager.GetString("text_PnPorcGastosF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Premium Price.
        /// </summary>
        public static string text_PnPremiumPriceM {
            get {
                return ResourceManager.GetString("text_PnPremiumPriceM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reconstrucción del producto.
        /// </summary>
        public static string text_PnReconstruccionM {
            get {
                return ResourceManager.GetString("text_PnReconstruccionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Redondeo.
        /// </summary>
        public static string text_PnRedondeoF {
            get {
                return ResourceManager.GetString("text_PnRedondeoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguro Internacional.
        /// </summary>
        public static string text_PnSeguroIntF {
            get {
                return ResourceManager.GetString("text_PnSeguroIntF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sensorizacion.
        /// </summary>
        public static string text_PnSensorizacionM {
            get {
                return ResourceManager.GetString("text_PnSensorizacionM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubLinea.
        /// </summary>
        public static string text_PnSubLineaS {
            get {
                return ResourceManager.GetString("text_PnSubLineaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tope Máximo.
        /// </summary>
        public static string text_PnTopeMaximoF {
            get {
                return ResourceManager.GetString("text_PnTopeMaximoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tope Mínimo.
        /// </summary>
        public static string text_PnTopeMinimoF {
            get {
                return ResourceManager.GetString("text_PnTopeMinimoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TRM.
        /// </summary>
        public static string text_PnTRMF {
            get {
                return ResourceManager.GetString("text_PnTRMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Falso.
        /// </summary>
        public static string text_PnValorFalsoF {
            get {
                return ResourceManager.GetString("text_PnValorFalsoF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Verdadero.
        /// </summary>
        public static string text_PnValorVerdaderoF {
            get {
                return ResourceManager.GetString("text_PnValorVerdaderoF", resourceCulture);
            }
        }
    }
}
